//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfg.banner
{
    public enum Quality
    {
        /// <summary>
        /// 白
        /// </summary>
        White = 0,
        /// <summary>
        /// 蓝
        /// </summary>
        Blue = 1,
        /// <summary>
        /// 紫
        /// </summary>
        Purple = 2,
        /// <summary>
        /// 金
        /// </summary>
        Glod = 3,
    }
}
