//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.banner
{

public sealed partial class TbBanner
{
    private readonly Dictionary<string, banner.Banner> _dataMap;
    private readonly List<banner.Banner> _dataList;
    
    public TbBanner(JSONNode _json)
    {
        _dataMap = new Dictionary<string, banner.Banner>();
        _dataList = new List<banner.Banner>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = banner.Banner.DeserializeBanner(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, banner.Banner> DataMap => _dataMap;
    public List<banner.Banner> DataList => _dataList;

    public banner.Banner GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public banner.Banner Get(string key) => _dataMap[key];
    public banner.Banner this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}