//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.banner
{

public sealed partial class Banner :  Bright.Config.BeanBase 
{
    public Banner(JSONNode _json) 
    {
        { if(!_json["id"].IsString) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["name"].IsString) { throw new SerializationException(); }  Name = _json["name"]; }
        { var _json1 = _json["bannerItemList"]; if(!_json1.IsArray) { throw new SerializationException(); } BannerItemList = new System.Collections.Generic.List<banner.MainBannerItem>(_json1.Count); foreach(JSONNode __e in _json1.Children) { banner.MainBannerItem __v;  { if(!__e.IsObject) { throw new SerializationException(); }  __v = banner.MainBannerItem.DeserializeMainBannerItem(__e); }  BannerItemList.Add(__v); }   }
        PostInit();
    }

    public Banner(string id, string name, System.Collections.Generic.List<banner.MainBannerItem> bannerItemList ) 
    {
        this.Id = id;
        this.Name = name;
        this.BannerItemList = bannerItemList;
        PostInit();
    }

    public static Banner DeserializeBanner(JSONNode _json)
    {
        return new banner.Banner(_json);
    }

    public string Id { get; private set; }
    public string Name { get; private set; }
    public System.Collections.Generic.List<banner.MainBannerItem> BannerItemList { get; private set; }

    public const int __ID__ = -484808626;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in BannerItemList) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in BannerItemList) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "BannerItemList:" + Bright.Common.StringUtil.CollectionToString(BannerItemList) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
