//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.banner
{

public abstract partial class basePowerItem :  Bright.Config.BeanBase 
{
    public basePowerItem(JSONNode _json) 
    {
        { if(!_json["power"].IsNumber) { throw new SerializationException(); }  Power = _json["power"]; }
        PostInit();
    }

    public basePowerItem(int power ) 
    {
        this.Power = power;
        PostInit();
    }

    public static basePowerItem DeserializebasePowerItem(JSONNode _json)
    {
        string type = _json["$type"];
        switch (type)
        {
            case "MainBannerItem": return new banner.MainBannerItem(_json);
            default: throw new SerializationException();
        }
    }

    public int Power { get; private set; }


    public virtual void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Power:" + Power + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
