//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.banner
{

public sealed partial class UpItem :  Bright.Config.BeanBase 
{
    public UpItem(JSONNode _json) 
    {
        { if(!_json["startTime"].IsNumber) { throw new SerializationException(); }  StartTime = _json["startTime"]; }
        { if(!_json["endTime"].IsNumber) { throw new SerializationException(); }  EndTime = _json["endTime"]; }
        { if(!_json["targetRate"].IsNumber) { throw new SerializationException(); }  TargetRate = _json["targetRate"]; }
        PostInit();
    }

    public UpItem(int startTime, int endTime, float targetRate ) 
    {
        this.StartTime = startTime;
        this.EndTime = endTime;
        this.TargetRate = targetRate;
        PostInit();
    }

    public static UpItem DeserializeUpItem(JSONNode _json)
    {
        return new banner.UpItem(_json);
    }

    public int StartTime { get; private set; }
    public int EndTime { get; private set; }
    public float TargetRate { get; private set; }

    public const int __ID__ = 71901552;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "StartTime:" + StartTime + ","
        + "EndTime:" + EndTime + ","
        + "TargetRate:" + TargetRate + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
