//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace cfg.banner
{

public sealed partial class UpList :  Bright.Config.BeanBase 
{
    public UpList(JSONNode _json) 
    {
        { if(!_json["upTargetRate"].IsNumber) { throw new SerializationException(); }  UpTargetRate = _json["upTargetRate"]; }
        { var __json0 = _json["list"]; if(!__json0.IsArray) { throw new SerializationException(); } List = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  List.Add(__v0); }   }
        PostInit();
    }

    public UpList(float upTargetRate, System.Collections.Generic.List<string> list ) 
    {
        this.UpTargetRate = upTargetRate;
        this.List = list;
        PostInit();
    }

    public static UpList DeserializeUpList(JSONNode _json)
    {
        return new banner.UpList(_json);
    }

    public float UpTargetRate { get; private set; }
    public System.Collections.Generic.List<string> List { get; private set; }

    public const int __ID__ = 71980795;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "UpTargetRate:" + UpTargetRate + ","
        + "List:" + Bright.Common.StringUtil.CollectionToString(List) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
